name: Update HTML from Google Sheet

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas gspread oauth2client openpyxl

      - name: Set GOOGLE_CREDENTIALS_JSON
        run: echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json

      - name: Run HTML Generator
        run: python generate_html.py

      - name: Commit and push HTML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Auto-update HTML from Google Sheet"
          git push
